spring.application.name=api

# Configura a porta da aplicação
server.port=8888


# Desabilita (por enquanto) o acesso a banco de dados
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://pooled.db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=99a1445a9e0ed0340a3ec1bcb61f84a97894e5e1f64cd99805d875767ae7a13d
spring.datasource.password=sk_rSlNiprt_1Ki6b1z3ubT1
